// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'package:yc_wallet/helper/reflectable.dart' as prefix0;
import 'package:yc_wallet/repository/apis/coinmaketcap/model/id_map/id_map.dart'
    as prefix1;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'IdMap',
            r'.IdMap',
            7,
            0,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => (
                      {id,
                      rank,
                      name,
                      symbol,
                      slug,
                      platform,
                      isActive,
                      firstHistoricalData,
                      lastHistoricalData}) =>
                  b
                      ? prefix1.IdMap(
                          firstHistoricalData: firstHistoricalData,
                          id: id,
                          isActive: isActive,
                          lastHistoricalData: lastHistoricalData,
                          name: name,
                          platform: platform,
                          rank: rank,
                          slug: slug,
                          symbol: symbol)
                      : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix1.IdMap.fromJson(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toJson': 0,
              r'id': 0,
              r'rank': 0,
              r'name': 0,
              r'symbol': 0,
              r'slug': 0,
              r'platform': 0,
              r'isActive': 0,
              r'firstHistoricalData': 0,
              r'lastHistoricalData': 0,
              r'copyWith': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'dart.core.Object with ._$IdMap',
            r'.dart.core.Object with ._$IdMap',
            583,
            1,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            -1,
            const {},
            const {},
            const {},
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toJson': 0,
              r'id': 0,
              r'rank': 0,
              r'name': 0,
              r'symbol': 0,
              r'slug': 0,
              r'platform': 0,
              r'isActive': 0,
              r'firstHistoricalData': 0,
              r'lastHistoricalData': 0,
              r'copyWith': 0
            })
      ],
      null,
      null,
      <Type>[
        prefix1.IdMap,
        const r.FakeType(r'.dart.core.Object with ._$IdMap')
      ],
      2,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'toJson': (dynamic instance) => instance.toJson,
        r'id': (dynamic instance) => instance.id,
        r'rank': (dynamic instance) => instance.rank,
        r'name': (dynamic instance) => instance.name,
        r'symbol': (dynamic instance) => instance.symbol,
        r'slug': (dynamic instance) => instance.slug,
        r'platform': (dynamic instance) => instance.platform,
        r'isActive': (dynamic instance) => instance.isActive,
        r'firstHistoricalData': (dynamic instance) =>
            instance.firstHistoricalData,
        r'lastHistoricalData': (dynamic instance) =>
            instance.lastHistoricalData,
        r'copyWith': (dynamic instance) => instance.copyWith
      },
      {},
      null,
      [
        const [
          0,
          0,
          const [
            #id,
            #rank,
            #name,
            #symbol,
            #slug,
            #platform,
            #isActive,
            #firstHistoricalData,
            #lastHistoricalData
          ]
        ],
        const [1, 0, null]
      ])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
